/* Test file for Juice::Variant
   Copyright (C) 2013 Jarryd Beck

Distributed under the Boost Software License, Version 1.0

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

  The copyright notices in the Software and this entire statement, including
  the above license grant, this restriction and the following disclaimer,
  must be included in all copies of the Software, in whole or in part, and
  all derivative works of the Software, unless such copies or derivative
  works are solely in the form of machine-executable object code generated by
  a source language processor.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
  DEALINGS IN THE SOFTWARE.

*/

#include <iostream>
#include <string>

#include <typeinfo>

#include <juice/variant.hpp>

using namespace juice;

typedef Variant<int, std::string> MyVariant;

class MyVisitor : public static_visitor<int>
{
  public:

  int
  operator()(int a) const
  {
    std::cout << "Visit int " << a << std::endl;
    return a;
  }

  int
  operator()(const std::string& s) const
  {
    return s.size();
  }

  int operator()() const
  {
    return 0;
  }
};

struct MyStruct
{
  MyStruct&
  operator=(MyStruct&& rhs)
  {
    if (this != &rhs)
    {
      x = rhs.x;
    }

    return *this;
  }

  MyStruct()
  {
  }

  MyStruct(MyStruct&&)
  {
  }

  int x;
};

typedef Juice::Variant<MyStruct, int> ComplexVariant;

struct Multiple
{
  template <typename A, typename B>
  void
  operator()(A a, B b) const
  {
    std::cout << "Multiple visitor" << std::endl;
    std::cout << typeid(A).name() << std::endl;
    std::cout << "(" << a << ", " << b << ")"
      << std::endl;
  }

  void
  operator()() const
  {
  }
};

void
foo()
{
  MyVariant a, b;

  bool c = a == b;
  (void)c;

  MyVisitor v;
  visit(v, a);
  visit(MyVisitor(), a);

  MyVariant s("hello");
  MyVariant t("goodbye");

  std::cout << "0 < 0: " << (a < b) << std::endl;
  std::cout << "goodbye < hello: " << (t < s) << std::endl;
  std::cout << "0 < hello: " << (a < s) << std::endl;
  std::cout << "hello < goodbye: " << (s < t) << std::endl;
  std::cout << "goodbye <= hello: " << (s <= t) << std::endl;
  std::cout << "0 <= 0: " << (a <= b) << std::endl;
  std::cout << "0 >= 0: " << (a >= b) << std::endl;

  ComplexVariant complexa;
  complexa = ComplexVariant(5);
  a = MyVariant();

  //auto delayed = apply_visitor(v);
  //delayed(a);

  Multiple m;
  visit(m, a, s);

  //use empty constructor
  MyVariant d(b);

  //empty assignment
  d = a;

  MyVariant emplaced(emplaced_index_t<1>(), "test");
}

int main(int argc, char** argv)
{
  foo();
  return 0;
}
